### PR TITLE
Add Laravel cache storage

### PR DESCRIPTION
**Pull request by M165437**
Thank your for creating this middleware! I added a storage file to use with Laravel as well as updated the example sections of the README file.

### CODE REVIEW

**Comment by Kevinrob** [comment]
Thank you!

**Comment by Kevinrob** [comment]
@M165437 Sorry, but your [example](https://github.com/Kevinrob/guzzle-cache-middleware#laravel-cache) doesn't work. `Cache::store('redis')` is not defined, did you miss a `use`?

Can you pull the master branch et test it?

**Comment by M165437** [comment]
I don't think so, works for me. `use Illuminate\Support\Facades\Cache;` should do it. Redis must of course be available on the machine and appropriately configured in `config/cache.php`.

**Comment by Kevinrob** [comment]
I have added `"illuminate/cache": "^5.0"` to the `composer.json`, is it correct?

**Comment by M165437** [comment]
No need to include it. It's a dependency of Laravel by default.

**Comment by M165437** [comment]
… but I did overlook that you will need to install the `predis/predis` package (~1.0) via Composer before using Redis with Laravel as [stated in the docs](https://laravel.com/docs/5.2/redis). `Cache::store('redis')` is only an example. Try using any other of [Laravel's cache options](https://laravel.com/docs/5.2/cache).

**Comment by Kevinrob** [comment]
Ok, thanks. I will try to install a Laravel project for testing :+1:

**Comment by Kevinrob** [comment]
I have tested. It's OK!
I am not familiar with Laravel, apparently it make some magic with `Facade`. But it's work! Thank you, I have released `v1.4` with it :+1: .

**Comment by M165437** [comment]
Thank _you_! :-)

**Pull request merged**
