### PR TITLE
POST request strategy key support

### PR DESCRIPTION
**Pull request by Legion112**
Will solve: https://github.com/Kevinrob/guzzle-cache-middleware/issues/170

### CODE REVIEW

**Comment by Legion112** [comment]
Any feedback? 
@kebingyu

**Comment by Legion112** [comment]
@Kevinrob any feedback?

**Review by Kevinrob — CHANGES_REQUESTED** [review]
As explained [in the issue](https://github.com/Kevinrob/guzzle-cache-middleware/issues/170#issuecomment-1564228505) linked, the cache should not intercept POST queries.

**Review by Kevinrob — CHANGES_REQUESTED** [review]
As body should be ignored for GET requests, I don't think it's okay to add this to the library.

You can keep a custom strategy on your codebase or maybe add a way to the library that let customise this on-demand.

PS: for the Docker related modifications, would you like to make a different PR with it?

**Comment by Legion112** [comment]
Sure I will created a separate SR with only docker commit.

**Comment by Legion112** [comment]
Here: https://github.com/Kevinrob/guzzle-cache-middleware/pull/179

**Comment by Kevinrob** [comment]
> It is strange that you have a way to set the cache methods
> 
> https://github.com/Kevinrob/guzzle-cache-middleware/blob/0e12dccf3c811a18bb2f6c93882c5b5727e1b859/src/CacheMiddleware.php#LL98C21-L98C35 `\Kevinrob\GuzzleCache\CacheMiddleware::setHttpMethods`
> 
> If you think the library should not allow to set cache for **post** method and others why not drop this method to prevent users from misusing it?

Yeah, that's because this lib can be extended with custom strategies. The strategies that are bundle with it respect the RFC, but people can use it as they want.

**Comment by Legion112** [comment]
I am not longer interested in this change.

**Pull request closed without merging**
