### PR TITLE
Add missing note on hard Doctrine\Cache dependency

### PR DESCRIPTION
**Pull request by Thinkscape**

### CODE REVIEW

**Comment by Kevinrob** [comment]
@Thinkscape is `Doctrine/Cache` an issue for you? Why did you say "works only with"?
You can implement the `Doctrine\Common\Cache\Cache` for using any other cache storage.

Do you think this library must not depend on `Doctrine/Cache`?

**Comment by Thinkscape** [comment]
There's myriad of other php caching frameworks. You've decided to go with `Doctrine\Cache` which is fine, but at least it has to be documented.

What I'd probably do is provide a simple "cache service" interface (might be partially compatible with Doctrine's approach) and leave that at it. This way you're not bound to one solution.

**Comment by Kevinrob** [comment]
Okay, you're right!
Thank you!

**Comment by Thinkscape** [comment]
:+1: 
If I decided to use your middleware for caching I'll write the interface + adapter for d2 and cachet.

**Comment by Kevinrob** [comment]
Feel free to open issue if necessary :+1:

**Pull request merged**
