### PR TITLE
Allow `guzzlehttp/psr7` to use version `^2.0.0`

### PR DESCRIPTION
**Pull request by hhamon**

### CODE REVIEW

**Comment by hannesvdvreken** [comment]
lgtm

**Comment by Kevinrob** [comment]
Thanks for this PR ✅

**Comment by xavierleune** [comment]
hi @Kevinrob, it seems that this changed has been merged but not released, can you please take a look at this ?

Thanks !

**Comment by Kevinrob** [comment]
> hi @Kevinrob, it seems that this changed has been merged but not released, can you please take a look at this ?
> 
> Thanks !

https://github.com/Kevinrob/guzzle-cache-middleware/releases/tag/v3.5.0
Done 😊

**Comment by xavierleune** [comment]
nice, thanks @Kevinrob !

**Pull request merged**
