### PR TITLE
Depend on contract instead of the implementation.

### PR DESCRIPTION
**Pull request by atehnix**

### CODE REVIEW

**Comment by atehnix** [comment]
Hey! Is there anybody here? :)

**Comment by Kevinrob** [comment]
Sorry for taking time to answer. 
I don't know Laravel, can you explain me a little bit the change? It's like an interface?

**Comment by atehnix** [comment]
Yes, this is an interface: [Illuminate/Contracts/Cache/Repository](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Contracts/Cache/Repository.php)
This is a concrete implementation: [Illuminate/Cache/Repository](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Cache/Repository.php)

**Comment by Kevinrob** [comment]
`v2.0.1` 😉

**Pull request merged**
