### PR TITLE
[FEATURE] delete function

### PR DESCRIPTION
**Pull request by Neirda24**

### CODE REVIEW

**Comment by Neirda24** [comment]
@jeromegamez : sorry forgot to add on Strategy Interface. I'll do it in 5minutes

**Comment by Neirda24** [comment]
@jeromegamez : is it good to be merged ?

**Comment by Neirda24** [comment]
@Kevinrob : is it ok ?

**Comment by Kevinrob** [comment]
Thank @Neirda24 ! I will take a look at it!

**Comment by Kevinrob** [comment]
The code seams good!
This PR is breaking "public API" (adding new methods to interfaces). So I will release a new major version.

**Comment by Neirda24** [comment]
Thanks @Kevinrob

**Pull request merged**
