### PR TITLE
fix typo public

### PR DESCRIPTION
**Pull request by josep11**

### CODE REVIEW

**Comment by DavidGoodwin** [comment]
i think 'private' was correct in this instance

**Comment by josep11** [comment]
> i think 'private' was correct in this instance

why, if it's PublicCacheStrategy?

**Comment by DavidGoodwin** [comment]
because it caches public things (i.e. NOT those things with private in their header) ?

**Review by Kevinrob — CHANGES_REQUESTED** [review]
Sorry, but I think that the current comment is correct!
`For example, a response with cache-control header "private, max-age=60" will be NOT cached by this strategy.`
This strategy will not cache private content.

As you don't understand well the current comment, would you like to clarify it?

**Comment by Kevinrob** [comment]
I am closing this PR with no activity. Don't hesitate to open a new one if necessary!

**Pull request closed without merging**
