### PR TITLE
add PSR-16 support

### PR DESCRIPTION
**Pull request by renanbr**

### CODE REVIEW

**Comment by renanbr** [comment]
Tests are green in PHP 5.6 and 7, but failing in those version:

- 5.5, because `cache/simple-cache-bridge` requires 5.6;
- HHVM, I have no idea what happens

I can go further if you consider this patch pertinent

**Comment by Kevinrob** [comment]
Nice! Thank you for the PR @renanbr !

HHVM isn't supported anymore by Doctrine\Cache... I think that I will remove it (see https://github.com/doctrine/cache/pull/219)
For PHP 5.5... Is it still used? 🤔

**Comment by Kevinrob** [comment]
@renanbr When you write `I can go further if you consider this patch pertinent`. What did you mean? Is there anything that you want to add before I merge the PR?

**Comment by renanbr** [comment]
I was talking about PHP 5.5 test failure, but I think I solved it changing `cache/simple-cache-bridge` constraint requirement from `^1.0` to `^0.1 || ^1.0`, because 0.1.0 works on PHP 5.5.

From my side it's ready to merge :-)

**Pull request merged**
