### PR TITLE
Update matrix with lowest & highest deps + PHP 8.0 & 8.1

### PR DESCRIPTION
**Pull request by xavierleune**

### CODE REVIEW

**Comment by xavierleune** [comment]
Rebased using @hhamon Pull request #152

**Comment by xavierleune** [comment]
I had to drop PHP < 7.2 and to update deps to reflect real expectations from code or tests.

**Comment by xavierleune** [comment]
Finally got something working on all versions :tada:

**Comment by hhamon** [comment]
Thanks @xavierleune :)

**Review by Kevinrob — APPROVED** [review]
Nice! Thank you 👍

**Pull request merged**
